config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from news.sitemaps import PostSitemap
from django.contrib.flatpages import views


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),
    path('advertise/', views.flatpage, {'url': '/advertise/'}, name='advertise'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', include('news.urls', namespace='news')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'National Trust CMS'
admin.site.index_title = 'Admin Dashboard'
admin.site.site_title = 'National Trust Administration'

handler500 = 'news.views.error_500'
handler404 = 'news.views.error_404'

news/urls.py
from django.urls import path
from .feeds import LatestPostsFeed
from . import views

app_name = 'news'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('archive/', views.archive, name='archive'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('tag/<slug:slug>/', views.tag, name='tag'),    
    path('category/<slug:slug>/', views.category, name='category'),    
    path('post/<slug:slug>/', views.post, name='post'),
    path('', views.home, name='home'),
]

templates/partials/_editor_profile_card.html
{% load static %}

<div class="team-box-style-1 pt-3">
    <div class="team-img">
        <img class="rounded-circle" src="{% static 'img/avatar.jpg' %}" alt="Editor" width="200" height="200">
    </div>
    <div class="team-content">
        <span class="mb-2 badge p-2 bg-danger">Editor</span>
        <h3 class="name">Martins Mejabi</h3>
        <span>08139776749</span>
        <span class="d-block">martinsmedeludo@gmail.com</span>
    </div>
</div>

templates/partials/_featured-middle-post-style-5.html
<div class="featured-middle-post-style-5">
    <div class="rt-post post-md style-5 grid-meta">
        <div class="post-img">
            <a href="/post/">
                <img src="https://placehold.it/1200x491" alt="post" width="1200" height="491">
            </a>
        </div>
        <div class="post-content">
            <a href="" class="rt-post-cat-normal">Top Story</a>
            <h3 class="post-title">
                <a href="/post/">
                    After Moon They ar Land CloseSpace
                    Get the best Really
                </a>
            </h3>
            <p>
                Ahen an unknown printer took a galley of type and scrambled imake
                type specimen book has survived not only five centurie.
            </p>
            <div class="post-meta">
                <ul>
                    <li>
                        <span class="rt-meta">
                            by <a href="" class="name">Willum Skeem</a>
                        </span>
                    </li>
                    <li>
                        <span class="rt-meta">
                            <i class="far fa-calendar-alt icon"></i>
                            DECEMBER 9, 2022
                        </span>
                    </li>
                    <li>
                        <span class="rt-meta">
                            <i class="fas fa-eye icon"></i>
                            3,250
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/_featured_news_box.html
{% load static %}
<div class="featured-news-box-style-1" style="position: relative;">
    <a href="{{ post.get_absolute_url }}">
        <img src="{% if post.image %}{{ post.image_thumbnail.url }}{% elif post.image_link %}{{ post.image_link }}{% else %}{% static 'img/post.png' %}{% endif %}" alt="{{ post.image_caption }}" width="612" height="488">
    </a>
    <div class="position-absolute text-start top-0 w-100 p-2"> <span class="badge p-2 bg-danger">{{ post.category }}</span>
    </div>
    <div class="inner">
        <div class="feature-content">
            <ul class="featured-list">
                <li>
                    <h4 class="post-title text-dark">
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title }}
                        </a>
                    </h4>
                    <div class="post-meta mb-3">
                        <ul>
                            <li>
                                <span class="rt-meta">
                                    By {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}National Trust{% endif %}
                                </span>
                            </li>
                            <li>
                                <span class="rt-meta">
                                    <i class="far fa-calendar-alt icon"></i>
                                    {{ post.created|date:"F j, Y" }}
                                </span>
                            </li>
                        </ul>
                    </div>
                    <p class="mb-0">
                        {{ post.body|truncatechars:130|striptags }}
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partials/_features.html
<div class="post-list-style-4 mb-4">
    <div class="post-item">
        <div class="rt-post post-md style-9 grid-meta">
            <div class="post-img">
                <a href="/post/">
                    <img src="https://placehold.it/696x491" alt="post" width="696" height="491">
                </a>
            </div>
            <div class="post-content">
                <a href="#" class="rt-cat-primary">Features</a>
                <h3 class="post-title">
                    <a href="/post/">
                        Hypnotherapy For Motivation Gett
                        ing The Drive Back
                    </a>
                </h3>
                <p>
                    Ahen an unknown printer took a galley of type and
                    scrambled imake
                    type specimen book has survived not only five
                    centurie.
                </p>
                <div class="post-meta">
                    <ul>
                        <li>
                            <span class="rt-meta">
                                by <a href="#" class="name">Seyi
                                    Pythonian</a>
                            </span>
                        </li>
                        <li>
                            <span class="rt-meta">
                                <i class="far fa-calendar-alt icon"></i>
                                DECEMBER 9, 2022
                            </span>
                        </li>
                        <li>
                            <span class="rt-meta">
                                <i class="fas fa-eye icon"></i>
                                3,250
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/_footer.html
<!-- Start Footer -->
<footer class="footer footer-style-5">    
    <div class="footer-top footer-style-1">
        <div class="container">
            <div class="row gy-5">
                <div class="col-xl-4 col-md-6 text-center text-md-start">
                    <div class="footer-widget">
                        <h1 class="fw-bold" style="color: #fff; font-family: 'Rowdies', cursive; font-size: 38px;">National Trust</h1>
                        <p class="text">
                            Abuja, Nigeria.<br>
                        </p>
                    </div>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div class="footer-widget">
                        <h3 class="footer-widget-title">Categories</h3>
                        <ul class="widget-list cat-list">
                            {% for c in categories %}
                            <li class="widget-list-item">
                                <a href="{{ c.get_absolute_url }}" class="widget-list-link">
                                    {{ c.title }}
                                </a>
                            </li>
                            {% empty %} 
                            <p>No categories yet.</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div class="row g-4">
                        <ul class="footer-social gutter-15">
                            <li class="social-item">
                                <a href="https://www.facebook.com/nationaltrustng" class="social-link fb" target="_blank">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                            </li>
                            <li class="social-item">
                                <a href="https://twitter.com/NationalTrustTV" class="social-link tw" target="_blank">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </li>
                            <li class="social-item">
                                <a href="https://www.youtube.com/channel/UCf6B4YZR82FBtztYKopM_UA" class="social-link pn" target="_blank">
                                    <i class="fab fa-youtube"></i>
                                </a>
                            </li>
                            <li class="social-item">
                                <a href="https://wa.me/2348116593333" class="social-link wh" target="_blank">
                                    <i class="fab fa-whatsapp"></i>
                                </a>
                            </li>
                        </ul>
                        <div class="col-12">
                            <div class="rt-subscribe-title-box-style-8">
                                <div class="title-wrap">
                                    <h3 class="title text-white">
                                        Subscribe To Our Mailing List
                                    </h3>
                                    <p>
                                        Get the news right tn your inbox
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 align-self-center">
            
                            <form action="" class="rt-contact-form subscribe-form-style-8">
                                <div class="rt-subs-group">
                                    <input type="email" name="email" id="email_2" class="subscribe-form" placeholder="Your e-mail"
                                        data-error="Email field is required" required>
                                    <button type="submit" class="subscribe-btn">Subscribe </button>
                                </div>
                                <div 1class="form-response"></div>
                            </form>
                        </div>
                    </div>
                    <div class="footer-widget">
                        <div class="sidebar-wrap my-5">
                            <div class="search-box">
                                {% include 'partials/_search.html' %}
                            </div>
                        </div>
                    </div>
                    <p>Send us a mail: <a href="mailto:nationaltrustng@gmail.com" class="text-primary">nationaltrustng@gmail.com</a></p>
                    <p><a href="https://www.nationaltrustng.com" class="text-primary">https://www.nationaltrustng.com</a></p>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="pt-5 row">
                <div class="col-12 col-md-6 text-center text-md-start order-2 order-md-1">
                    <p class="copyright-text mb-4 mb-md-0">
                        &copy;{% now "Y" %} &bull; National Trust Nigeria. All rights reserved.
                    </p>
                </div>
                <div class="col-12 col-md-6 order-1 order-md-2">
                    <ul class="footer-menu-style-2">
                        <li><a href="/about/">About us</a></li>
                        <li><a href="/contact/">Submit a story</a></li>
                        <li><a href="/advertise/">Advertise with us</a></li>
                        <li><a href="/privacy/">Privacy</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
</footer>
<!-- End  Footer -->

templates/partials/_latest_story.html
<div class="featured-middle-post-style-5">
    <div class="rt-post post-md style-5 grid-meta">
        <div class="post-img">
            <a href="/post/">
                <img src="https://placehold.it/1200x491" alt="post" width="1200" height="491">
            </a>
        </div>
        <div class="post-content">
            <a href="" class="rt-post-cat-normal">Latest Story</a>
            <h3 class="post-title">
                <a href="/post/">
                    After Moon They ar Land CloseSpace
                    Get the best Really
                </a>
            </h3>
            <p>
                Ahen an unknown printer took a galley of type and scrambled imake
                type specimen book has survived not only five centurie.
            </p>
            <div class="post-meta">
                <ul>
                    <li>
                        <span class="rt-meta">
                            by <a href="" class="name">Seyi Pythonian</a>
                        </span>
                    </li>
                    <li>
                        <span class="rt-meta">
                            <i class="far fa-calendar-alt icon"></i>
                            DECEMBER 9, 2022
                        </span>
                    </li>
                    <li>
                        <span class="rt-meta">
                            <i class="fas fa-eye icon"></i>
                            3,250
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/_navbar.html
<!-- Header Main -->
<div class="header-main header-main-style-5 navbar-wrap text-white" id="navbar-wrap">
    <div class="container">
        <div class="row">
            <ul class="header-action-items d-sm-none pt-3">
                <li class="rt-meta me-3">
                    <i class="far fa-calendar-alt icon"></i>
                    <span class="text-dark">{% now "l, F j, Y" %}</span>
                </li>
                <li class="rt-meta">
                    <i class="fas fa-map-marker icon"></i>
                    <span class="text-dark">Abuja, Nigeria.</span>
                </li>
            </ul>
            <div class="header-action-bars d-flex align-items-center justify-content-between">

                <ul class="header-action-items d-none d-sm-block">
                    <li class="rt-meta">
                        <i class="far fa-calendar-alt icon"></i>
                        <span class="text-dark">{% now "l, F j, Y" %}</span>
                    </li>
                </ul>
                
                <div class="site-branding">
                    <a href="/"><h1 class="fw-bold text-primary" style="font-family: 'Rowdies', cursive; font-size: 38px;">National Trust</h1></a>
                </div>
                <ul class="header-action-items">
                    <li class="item humburger offcanvas-menu-btn menu-status-open text-dark">
                        <span></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="offcanvas-menu-wrap offcanvas-menu-wrap-style-2" id="offcanvas-wrap" data-position="left">

    <div class="offcanvas-content offcanvas-content-style-2">

        <div class="offcanvas-top-area">
            <div class="offcanvas-header">
                <div class="offcanvas-logo">
                    <a href="/">
                        <h3 class="fw-bold text-primary" style="font-family: 'Rowdies', cursive; font-size: 25px;">National Trust</h3>
                    </a>
                </div>
                <div class="close-btn offcanvas-close">
                    <a href="javascript:void(0)">
                        <i class="fas fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="offscreen-navigation">
                <nav class="menu-main-primary-container">
                    <ul class="menu">
                        <li class="list">
                            <a href="/">Home</a>
                        </li>
                        <li class="list">
                            <a href="/about/">About us</a>
                        </li>
                        <li class="list">
                            <a href="/contact/">Submit a Story</a>
                        </li>
                        <li class="list">
                            <a href="/advertise/">Advertise with us</a>
                        </li>
                        <li class="list">
                            <a href="/privacy/">Privacy</a>
                        </li>
                    </ul>
                </nav>
            </div>

        </div>

        <div class="offcanvas-bottom-area">
            <div class="offcanvas-widget footer-widget">
                <h3 class="offcanvas-widget-title">Contact Info</h3>
                <ul class="contact-info-list widget-list">
                    <li class="widget-list-item">
                        <i class="fas fa-phone-alt list-icon"></i>
                        <a href="tel:08116593333" class="widget-list-link">
                            (+234) 08116593333
                        </a>
                    </li>
                    <li class="widget-list-item">
                        <i class="fas fa-map-marker list-icon"></i>
                        <a href="javascript:void(0)" class="widget-list-link">
                            Abuja, Nigeria
                        </a>
                    </li>
                    <li class="widget-list-item">
                        <i class="fas fa-envelope list-icon"></i>
                        <a href="mailto:nationaltrustng@gmail.com" class="widget-list-link">
                            nationaltrustng@gmail.com
                        </a>
                    </li>
                </ul>
            </div>
            <div class="offcanvas-widget footer-widget">
                <ul class="footer-social style-2">
                    <li class="social-item">
                        <a href="https://www.facebook.com/nationaltrustng" class="social-link fb" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="social-item">
                        <a href="https://twitter.com/NationalTrustTV" class="social-link tw" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="social-item">
                        <a href="https://www.youtube.com/channel/UCf6B4YZR82FBtztYKopM_UA" class="social-link vm" target="_blank">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </li>
                    <li class="social-item">
                        <a href="https://wa.me/2348116593333" class="social-link wh" target="_blank">
                            <i class="fab fa-whatsapp"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/partials/_news_list_style-1.html
<div class="item">
    <div class="item-content">
        <a href="#" class="rt-post-cat-normal">Politics</a>
        <h4 class="post-title">
            <a href="/post/">
                After Moon They Land lower
                CloseSpace Really?
            </a>
        </h4>
        <span class="rt-meta">
            <i class="far fa-calendar-alt icon"></i>
            DECEMBER 9, 2022
        </span>
    </div>
</div>

templates/partials/_personality.html
<div class="rt-post post-md style-8">
    <div class="post-img">
        <a href="/post/">
            <img src="https://placehold.it/551x430" alt="post" width="551" height="430">
        </a>
    </div>
    <div class="post-content">
        <a href="#" class="ft-yoga">Personality</a>
        <h4 class="post-title">
            <a href="/post/">
                Our Ultimatey Top Hikes
                in New Zealand
            </a>
        </h4>
        <span class="rt-meta">
            <i class="far fa-calendar-alt icon"></i>
            DECEMBER 9, 2022
        </span>
    </div>
</div>

templates/partials/_post_grid_1.html
{% load static %}
<div class="item">
    <div class="item-content" style="position: relative;">
        <div class="post-img me-0 mb-2">
            <a href="{{ post.get_absolute_url }}">
                <img src="{% if post.image %}{{ post.image_thumbnail.url }}{% elif post.image_link %}{{ post.image_link }}{% else %}{% static 'img/post.png' %}{% endif %}" alt="post" width="551" height="431">
            </a>
        </div>
        <div class="position-absolute text-start top-0 w-100 p-2"> <span class="badge p-2 bg-danger">{{ post.category }}</span> </div>
        <h4 class="post-title text-dark">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h4>
        <span class="rt-meta me-2">
            By {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}National Trust{% endif %}
        </span>
        <span class="rt-meta">
            <i class="far fa-calendar-alt icon"></i>
            {{ post.created|date:"F j, Y" }}
        </span>
    </div>
</div>

templates/partials/_post_grid_columnist.html
<div class="rt-post-grid grid-meta">
    <div class="post-img">
        <a href="/post/">
            <img src="https://placehold.it/551x430" alt="post" width="551" height="430">
        </a>
        <a href="#" class="ft-fit rt-meta-over">Africa</a>
    </div>
    <div class="post-content">
        <h3 class="post-title">
            <a href="/post/">
                Magical fisher basical navik
                power to conjure
            </a>
        </h3>
        <div class="post-meta">
            <ul>
                <li>
                    <span class="rt-meta">
                        By <a href="#" class="name">Admin</a>
                    </span>
                </li>
                <li>
                    <span class="rt-meta">
                        <i class="far fa-calendar-alt icon"></i>
                        DECEMBER 9, 2022
                    </span>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partials/_post_md.html
<div class="rt-post post-md style-8">
    <div class="post-img">
        <a href="#">
            <img src="https://placehold.it/551x430" alt="post" width="551" height="430">
        </a>
    </div>
    <div class="post-content">
        <a href="#" class="ft-yoga">Security</a>
        <h4 class="post-title">
            <a href="#">
                Our Ultimatey Top Hikes
                in New Zealand
            </a>
        </h4>
        <span class="rt-meta">
            <i class="far fa-calendar-alt icon"></i>
            DECEMBER 9, 2022
        </span>
    </div>
</div>

templates/partials/_search.html
<form action="{% url 'news:search' %}" class="form search-form-box">
    <div class="form-group">
        <input type="text" name="q" id="search" placeholder="Search..." class="form-control rt-search-control"
            value="{{ request.GET.q }}">
        <button type="submit" class="search-submit">
            <i class="fas fa-search"></i>
        </button>
    </div>
</form>

templates/partials/_topbar2.html
<style>
    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: nowrap;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .nav-scroller .nav a {
        color: firebrick !important;
    }

    .nav-scroller .nav a:hover {
        color: #000 !important;
    }

    .flex-auto {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 auto;
        flex: 0 0 auto;
    }
    .topbar2 {
        min-height: 50px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
            -ms-flex-align: center;
                align-items: center;
    }
</style>

<div class="topbar2">
    <div class="container">
        <div class="row align-items-center">
            <div class="nav-scroller py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <a class="py-2 pe-4 text-decoration-none {% url 'news:home' as home_url %}{% if request.get_full_path == home_url %}active{% endif %}" href="{{ home_url }}">Home</a>
                    {% for c in categories %}
                    <a class="py-2 {% if forloop.last %}ps-2{% else %}pe-4{% endif %} text-decoration-none" href="{{ c.get_absolute_url }}">{{ c.title }}</a>
                    {% endfor %}
                </nav>
            </div>
        </div>
    </div>
</div>